/**
 * @file tests/exports.test.ts
 * @desc The public surface: exactly these runtime exports, so an accidental export or removal
 *       shows up in review as a semver question.
 * @author David @dvhsh (https://dvh.sh)
 * @created Wed Sep 23, 2026
 * @modified Wed Sep 23, 2026
 */

import { expect, it } from "vitest";
import * as api from "../src/index.js";

it("exports the documented runtime API", () => {
  expect(Object.keys(api).sort()).toMatchInlineSnapshot(`
    [
      "BEATMAP_REF_MESSAGES",
      "BUCKET_CODE_MESSAGES",
      "BUCKET_CODE_PATTERN",
      "DEFAULT_BUCKETS",
      "MAX_BUCKET_CODE_LENGTH",
      "MAX_CUSTOM_BUCKETS",
      "MAX_FORCED_MODS",
      "MAX_NAME_LENGTH",
      "MAX_SLOTS",
      "MAX_SLOT_INDEX",
      "MOD_ACRONYMS",
      "MOD_BUCKETS",
      "MOD_BUCKET_NAMES",
      "MOD_SET_MESSAGES",
      "NO_MODS",
      "NO_SLOT_NAME",
      "PACK_KEY_ERROR_MESSAGES",
      "PACK_KEY_VERSIONS",
      "PALETTE",
      "PALETTE_SIZE",
      "POOL_LINE_HELP",
      "PackKeyError",
      "RULESETS",
      "addBucket",
      "addBuckets",
      "addSlot",
      "beatmapIdSchema",
      "bitmaskToMods",
      "bucketCodeSchema",
      "bucketEntrySchema",
      "bucketName",
      "bucketOptionLabel",
      "bucketsOf",
      "builtInBucketSchema",
      "canonicalBuckets",
      "checkBucketCode",
      "checkPoolBuckets",
      "customBucketSchema",
      "decodePackKey",
      "encodePackKey",
      "extractPackKey",
      "findBucket",
      "freemodSets",
      "insertBeforeTb",
      "isCustomBucket",
      "isModAcronym",
      "isModBucket",
      "matchBucketCode",
      "mergeSlots",
      "modAcronymSchema",
      "modBlockedReason",
      "modSetProblem",
      "modSetsFor",
      "modsLabel",
      "modsToBitmask",
      "moveBucket",
      "moveSlot",
      "nextFreeColor",
      "nextSlotIndex",
      "paletteColorSchema",
      "parseBeatmapRef",
      "parsePoolText",
      "planMerge",
      "poolDraftSchema",
      "poolFields",
      "poolSchema",
      "poolSlotSchema",
      "recolorBucket",
      "removeBucket",
      "removeSlot",
      "renameBucket",
      "setBucketMods",
      "slotKey",
      "slotLabel",
      "slotModsFor",
      "slotModsSummary",
      "slotTitle",
      "sortSlots",
      "storedSlotModsSchema",
      "toggleMod",
      "withBuckets",
    ]
  `);
});
